version: '2'
services:
  jhipsterappsample-app:
    image: jhipsterappsample
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://jhipsterappsample-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=jhipsterappsample
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://jhipsterappsample-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://jhipsterappsample-elasticsearch:9200
    ports:
      - 8080:8080
  jhipsterappsample-mongodb:
    extends:
      file: mongodb.yml
      service: jhipsterappsample-mongodb
  jhipsterappsample-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: jhipsterappsample-elasticsearch
